"use client";

import * as React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { recentAlerts } from "@/lib/mock-data";
import { AlertsTable } from "./components/alerts-table";
import type { Alert } from "@/lib/types";


export default function AlertsPage() {
  const [alerts, setAlerts] = React.useState<Alert[]>(recentAlerts);

  const handleStatusChange = (alertId: string, newStatus: Alert["status"]) => {
    setAlerts(
      alerts.map((alert) =>
        alert.id === alertId ? { ...alert, status: newStatus } : alert
      )
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Alert Triage Center</CardTitle>
        <CardDescription>
          Investigate, prioritize, and manage all security alerts generated by
          the platform.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <AlertsTable alerts={alerts} onStatusChange={handleStatusChange} />
      </CardContent>
    </Card>
  );
}
