import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AlertsTable } from "./components/alerts-table";
import type { Alert } from "@/lib/types";

export const dynamic = 'force-dynamic';
const API_URL = process.env.NEXT_PUBLIC_API_URL;

async function getAlerts(): Promise<Alert[]> {
  const res = await fetch(`${API_URL}/api/alerts`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch alert data');
  return res.json();
}

export default async function AlertsPage() {
  const alerts = await getAlerts();
  return (
    <Card>
      <CardHeader>
        <CardTitle>Alert Triage Center</CardTitle>
        <CardDescription>
          Investigate, prioritize, and manage all security alerts generated by
          the platform.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {alerts.length > 0 ? (
          <AlertsTable initialAlerts={alerts} />
        ) : (
          <div className="flex items-center justify-center h-48 border border-dashed rounded-md">
            <p className="text-muted-foreground">No alerts found.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
