import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { recentAlerts } from "@/lib/mock-data";
import { AlertsTable } from "./components/alerts-table";

export default function AlertsPage() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Alert Triage Center</CardTitle>
        <CardDescription>
          Investigate, prioritize, and manage all security alerts generated by
          the platform.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <AlertsTable initialAlerts={recentAlerts} />
      </CardContent>
    </Card>
  );
}
