# Configuration for the Sysmon Sentinel Agent

agent_id = "agent-007"

[server]
# Using HTTP for QA testing due to SSL issues
url = "http://localhost:3000" 

# Security section is now ignored by the agent when using HTTP
[security]
server_cert_path = ""
agent_cert_path = ""
agent_key_path = ""
